name: Предложение
description: Новая возможность или улучшение
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу это решает
      description: Что вы делаете сейчас и что неудобно.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Как это могло бы выглядеть
